apiVersion: v1
kind: Template
labels:
  template: search-api-template
message: |-
  A Jenkins server must be instantiated in this project to manage
  the Pipeline BuildConfig created by this template. You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    openshift.io/display-name: digitalforms-api template
    description: |-
      This is a template for digitalforms-api.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: digitalforms-api-template
parameters:
- description: The OpenShift Namespace prefix.
  displayName: Namespace Prefix (Prefix for each namespace ie prefix-tools, prefix-dev etc)
  name: namespacePrefix
  required: true
  value:
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    labels:
      app: digitalforms-api
      template: master-build-pipeline
    name: digitalforms-api
    namespace: ${namespacePrefix}-tools
  spec:
    completionDeadlineSeconds: 1800
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: digitalforms-api:latest
    postCommit: {}
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 1Gi
    runPolicy: Serial
    source:
      contextDir: ./digitalforms-api
      git:
        ref: master
        uri: https://github.com/bcgov/jag-rsbc-digital-forms-vips-integration
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: DIGITALFORMS_SWAGGER_ENABLED
            value: 'true'
          - name: NEXUS_URL
            valueFrom:
              secretKeyRef:
                key: NEXUS_URL
                name: nexus-config
          - name: NEXUS_ADMIN_USER
            valueFrom:
              secretKeyRef:
                key: NEXUS_ADMIN_USER
                name: nexus-config
          - name: NEXUS_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: NEXUS_ADMIN_PASSWORD
                name: nexus-config
        from:
          kind: ImageStreamTag
          name: java-s2i:17
          namespace: ${namespacePrefix}-tools
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers: []
