apiVersion: v1
kind: Template
labels:
  template: cucumber-maven-config
message: |-
  cucumber-maven config template.
metadata:
  annotations:
    description: |-
      cucumber-maven config template.
    tags: cucumber-maven-config
    template: cucumber-maven-config
  name: cucumber-maven-config

# Parameters
parameters:
- name: file
  required: true
  value: "c2V0LmZpbGU="
# Objects
objects:

- apiVersion: v1
  data:
    filename: >-
      ${file}
  kind: Secret
  metadata:
    name: cucumber-maven-config
    labels:
      credential.sync.jenkins.openshift.io: 'true'