apiVersion: v1
kind: Template
labels:
  template: digitalforms-api-webhook-config
message: |-
  digitalforms-api webhook configuration template.
metadata:
  annotations:
    description: |-
      digitalforms-api webhook configuration template.
    tags: digitalforms-api-webhook-config
    template: digitalforms-api-webhook-config
  name: digitalforms-api-webhook-config

# Parameters
parameters:
- name: DIGITALFORMS_BASICAUTH_PASSWORD
  required: true
  from: "[a-zA-Z0-9]{16}"
  generate: expression
- name: DIGITALFORMS_BASICAUTH_USER
  required: true
  value: "set.value"
- name: DIGITALFORMS_SWAGGER_ENABLED
  required: true
  value: "set.value"
- name: DIGITALFORMS_VIPSORDS_BASEPATH
  required: true
  value: "set.value"
- name: DIGITALFORMS_VIPSORDS_USER
  required: true
  value: "set.value"
- name: DIGITALFORMS_VIPSORDS_PASSWORD
  required: true
  value: "set.value"
- name: SPRING_PROFILES_ACTIVE
  required: true
  value: "set.value"
- name: DIGITALFORMS_ORDS_BASEPATH
  required: true
  value: "set.value"
- name: DIGITALFORMS_ORDS_USER
  required: true
  value: "set.value"
- name: DIGITALFORMS_ORDS_PASSWORD
  required: true
  value: "set.value"

# Objects
objects:

- apiVersion: v1
  stringData:
    DIGITALFORMS_BASICAUTH_PASSWORD: ${DIGITALFORMS_BASICAUTH_PASSWORD}
    DIGITALFORMS_BASICAUTH_USER: ${DIGITALFORMS_BASICAUTH_USER}
    DIGITALFORMS_SWAGGER_ENABLED: ${DIGITALFORMS_SWAGGER_ENABLED}
    DIGITALFORMS_VIPSORDS_BASEPATH: ${DIGITALFORMS_VIPSORDS_BASEPATH}
    DIGITALFORMS_VIPSORDS_USER: ${DIGITALFORMS_VIPSORDS_USER}
    DIGITALFORMS_VIPSORDS_PASSWORD: ${DIGITALFORMS_VIPSORDS_PASSWORD}
    SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    DIGITALFORMS_ORDS_BASEPATH: ${DIGITALFORMS_ORDS_BASEPATH}
    DIGITALFORMS_ORDS_USER: ${DIGITALFORMS_ORDS_USER}
    DIGITALFORMS_ORDS_PASSWORD: ${DIGITALFORMS_ORDS_PASSWORD}
  kind: Secret
  metadata:
    name: digitalforms-api