swagger: '2.0'
info:
  title: ORDS generated API for web
  version: 1.0.0
host: dev.jag.gov.bc.ca
basePath: "/ords/deva/rsdfrmords/web"
schemes:
- https
produces:
- application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication.
paths:
  "/health":
    get:
      tags:
      - Health
      security:
      - basicAuth: []
      operationId: health
      description: Dummy endpoint to check that API calls are working
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/healthOrdsResponse'
  "/digitalForm":
    post:
      tags:
      - Application
      security:
      - basicAuth: []
      description: Create digital form
      responses:
        '200':
          description: output of the endpoint
          schema:
            "$ref": "#/definitions/digitalFormCreateResponse"
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/digitalFormErrorResponse'
      parameters:
      - name: payload
        in: body
        required: true
        schema:
          "$ref": "#/definitions/digitalFormPostRequest"
  "/digitalForm/{guid}":
    get:
      tags:
      - Application
      security:
      - basicAuth: []
      description: Get digital form
      responses:
        '200':
          description: output of the endpoint
          schema:
            "$ref": "#/definitions/digitalFormGetResponse"
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/digitalFormErrorResponse'
      parameters:
      - name: guid
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
    patch:
      tags:
      - Application
      security:
      - basicAuth: []
      description: Patch digital form
      responses:
        '200':
          description: output of the endpoint
          schema:
            "$ref": "#/definitions/digitalFormPatchResponse"
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/digitalFormErrorResponse'
      parameters:
      - name: guid
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
      - name: payload
        in: body
        required: true
        schema:
          "$ref": "#/definitions/digitalFormPatchRequest"
  "/digitalForm/prohibition/{noticeNo}/payment":
    patch:
      tags:
      - Payment
      security:
      - basicAuth: []
      description: Patch payment details
      responses:
        '200':
          description: output of the endpoint
          schema:
            "$ref": "#/definitions/digitalFormPaymentPatchResponse"
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/digitalFormErrorResponse'
      parameters:
      - name: noticeNo
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
      - name: payload
        in: body
        required: true
        schema:
          "$ref": "#/definitions/digitalFormPaymentPatchRequest"
  "/digitalForm/prohibition/{noticeNo}/payment/status":
    get:
      tags:
      - Payment
      security:
      - basicAuth: []
      description: Get payment status
      responses:
        '200':
          description: output of the endpoint
          schema:
            "$ref": "#/definitions/digitalFormPaymentStatusResponse"
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/digitalFormErrorResponse'
      parameters:
      - name: noticeNo
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
  "/digitalForm/availableTimeSlot/{reviewDate}/{noticeTypeCd}/{reviewTypeCd}/{authGuid}/{correlationGuid}":
    get:
      tags:
      - Time Slots
      security:
      - basicAuth: []
      description: Get available time slots for a date
      responses:
        '200':
          description: available time slots
          schema:
            "$ref": "#/definitions/availableTimeSlotResponse"
      parameters:
      - name: authGuid
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
      - name: correlationGuid
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
      - name: noticeTypeCd
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
      - name: reviewDate
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
      - name: reviewTypeCd
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
  "/digitalForm/prohibition/{noticeNo}/review/schedule/{authGuid}/{correlationGuid}":
    post:
      tags:
      - Time Slots
      security:
      - basicAuth: []
      description: Save a review date time
      responses:
        '200':
          description: output of the endpoint
          schema:
            "$ref": "#/definitions/reviewTimeSlotResponse"
      consumes:
      - application/json
      parameters:
      - name: authGuid
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
      - name: correlationGuid
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
      - name: noticeNo
        in: path
        required: true
        type: string
        description: implicit
        pattern: "^[^/]+$"
      - name: payload
        in: body
        required: true
        schema:
          "$ref": "#/definitions/reviewTimeSlotRequest"
definitions:
  healthOrdsResponse:
    type: object
    required:
    - appid
    - method
    - status
    - host
    - instance
    properties:
      appid:
        type: string
      method:
        type: string
      status:
        type: string
      host:
        type: string
      instance:
        type: string
  digitalFormPostRequest:
    type: object
    required: 
    - user_id
    - prohibition_notice_no
    - correlation_guid
    - notice_subject_cd
    - notice_type_cd
    - review_application_type_cd
    - presentation_format_cd
    - review_role_type_cd
    - first_given_nm
    - second_given_nm
    - surname_nm
    - phone_no
    - fax_no
    - electronic_address_txt
    - manual_entry_yn
    - form_xml
    properties:
      user_id:
        type: string
      prohibition_notice_no:
        type: string
      correlation_guid:
        type: string
      notice_subject_cd:
        type: string
      notice_type_cd:
        type: string
      review_application_type_cd:
        type: string
      presentation_format_cd:
        type: string
      review_role_type_cd:
        type: string
      hearing_dt:
        type: string
      hearing_start_tm:
        type: string
      hearing_end_tm:
        type: string
      application_received_dt:
        type: string
      receipt_number_txt:
        type: string
      first_given_nm:
        type: string
      second_given_nm:
        type: string
      surname_nm:
        type: string
      phone_no:
        type: string
      fax_no:
        type: string
      electronic_address_txt:
        type: string
      manual_entry_yn:
        type: string
      form_xml:
        type: string
  digitalFormPatchRequest:
    type: object
    required: 
    - user_id
    properties:
      user_id:
        type: string
      prohibition_notice_no:
        type: string
      notice_subject_cd:
        type: string
      notice_type_cd:
        type: string
      review_application_type_cd:
        type: string
      presentation_format_cd:
        type: string
      review_role_type_cd:
        type: string
      hearing_dt:
        type: string
      hearing_start_tm:
        type: string
      hearing_end_tm:
        type: string
      application_received_dt:
        type: string
      receipt_number_txt:
        type: string
      first_given_nm:
        type: string
      second_given_nm:
        type: string
      surname_nm:
        type: string
      phone_no:
        type: string
      fax_no:
        type: string
      electronic_address_txt:
        type: string
      manual_entry_yn:
        type: string
      form_xml:
        type: string
  digitalFormGetResponse:
    type: object
    required: 
    - user_id
    - prohibition_notice_no
    - notice_subject_cd
    - notice_type_cd
    - review_application_type_cd
    - presentation_format_cd
    - review_role_type_cd
    - first_given_nm
    - second_given_nm
    - surname_nm
    - phone_no
    - fax_no
    - electronic_address_txt
    - manual_entry_yn
    - form_xml
    properties:
      status_code:
        type: string
      status_message:
        type: string
      user_id:
        type: string
      prohibition_notice_no:
        type: string
      notice_subject_cd:
        type: string
      notice_type_cd:
        type: string
      review_application_type_cd:
        type: string
      presentation_format_cd:
        type: string
      review_role_type_cd:
        type: string
      first_given_nm:
        type: string
      second_given_nm:
        type: string
      surname_nm:
        type: string
      phone_no:
        type: string
      fax_no:
        type: string
      electronic_address_txt:
        type: string
      manual_entry_yn:
        type: string
      form_xml:
        type: string
  digitalFormCreateResponse:
    type: object
    required:
    - status_code
    - status_message
    - form_object_guid
    - ent_dtm
    properties:
      status_code:
        type: string
      status_message:
        type: string
      form_object_guid:
        type: string
      ent_dtm:
        type: string
  digitalFormPatchResponse:
    type: object
    required:
    - status_code
    - status_message
    - form_object_guid
    - upd_dtm
    properties:
      status_code:
        type: string
      status_message:
        type: string
      form_object_guid:
        type: string
      upd_dtm:
        type: string
  digitalFormPaymentPatchRequest:
    type: object
    required:
    - payment_dtm
    - payment_card_type_txt
    - payment_amt
    - receipt_number_txt
    properties:
      payment_dtm:
        type: string
      payment_card_type_txt:
        type: string
      payment_amt:
        type: string
      receipt_number_txt:
        type: string
  digitalFormPaymentPatchResponse:
    type: object
    required:
    - status_code
    - status_message
    - upd_dtm
    properties:
      status_code:
        type: string
      status_message:
        type: string
      upd_dtm:
        type: string
  digitalFormPaymentStatusResponse:
    type: object
    required:
    - status_code
    - status_message
    - payment_dtm
    - payment_card_type_txt
    - payment_amt
    - receipt_number_txt
    properties:
      status_code:
        type: string
      status_message:
        type: string
      payment_dtm:
        type: string
      payment_card_type_txt:
        type: string
      payment_amt:
        type: string
      receipt_number_txt:
        type: string
  digitalFormErrorResponse:
    type: object
    required:
    - status_code
    - status_message
    properties:
      status_code:
        type: string
      status_message:
        type: string
  availableTimeSlotResponse:
    type: object
    required:
    - status_code
    - status_message
    - time_slots
    properties:
      status_code:
        type: string
      status_message:
        type: string
      time_slots:
        type: array
        items:
          type: object
          properties:
            review_start_dtm:
              type: string
            review_end_dtm:
              type: string
  reviewTimeSlotRequest:
    type: object
    required: 
    - review_start_dtm
    - review_end_dtm
    properties:
      review_start_dtm:
        type: string
      review_end_dtm:
        type: string
  reviewTimeSlotResponse:
    type: object
    required:
    - status_code
    - status_message
    - review_start_dtm
    - review_end_dtm
    properties:
      status_code:
        type: string
      status_message:
        type: string
      review_start_dtm:
        type: string
      review_end_dtm:
        type: string