apiVersion: v1
kind: Template
labels:
  template: jave-image-stream-template
message: |-
  A Jenkins server must be instantiated in this project to manage
  the Pipeline BuildConfig created by this template. You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    openshift.io/display-name: java image stream template
    description: |-
      This is a template for java image stream.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: imagestream-template
parameters:
- description: The OpenShift Namespace prefix.
  displayName: Namespace Prefix (Prefix for each namespace ie prefix-tools, prefix-dev etc)
  name: namespacePrefix
  required: true
  value:
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: java
    name: java-s2i
    namespace: ${namespacePrefix}-tools
  spec:
    tags:
      - annotations:
          description: Java s2i image
          tags: java-s2i
        from:
          kind: DockerImage
          name: "registry.access.redhat.com/ubi8/openjdk-17-runtime:1.18-2"
        name: "17"
