name: Main - Build Image and Push to Openshift Registry for Dev Deployment

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch: {}

jobs:
  commit-version:
    uses: SierraSystems/reusable-workflows/.github/workflows/get-github-commitversion.yml@main
    with:
      working_directory: .

  build-image:
    uses: SierraSystems/reusable-workflows/.github/workflows/openshift-source-to-image.yml@main
    needs:
      - commit-version
    with:
      build_config_name: "digitalforms-api"
      image_tags: "dev,${{ needs.commit-version.outputs.github-release-version }}"
    secrets:
      openshift_namespace: "${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools"
      openshift_server_url: "${{ secrets.OPENSHIFT_SERVER_URL_SILVER }}"
      openshift_token: "${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}"
      openshift_external_repository: "${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}"

  trivy:
    name: Trivy Scan Image
    needs:
      - build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to OpenShift Container Repository
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}
          username: ${{ secrets.OPENSHIFT_SA_PIPELINE_NAME_SILVER }}
          password: ${{ secrets.OPENSHIFT_SA_PIPELINE_TOKEN_SILVER }}
      
      - name: Pull Image for Scanning
        env:
          IMAGE: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}/${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools/digitalforms-api:dev
        run: |
          docker pull ${IMAGE}

      - name: Run Trivy vulnerability scanner - stdout
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER }}/${{ secrets.OPENSHIFT_LICENSE_PLATE_SILVER }}-tools/digitalforms-api:dev
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: HIGH,CRITICAL
