name: Main - Build Image and Push to Openshift Registry for Dev Deployment

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Image Target Env'
        required: true
        default: 'dev'

jobs:
  get-github-commitversion:
    uses: SierraSystems/reusable-workflows/.github/workflows/get-github-commitversion.yml@main
    with:
      working_directory: .