name: Build & Vulnerability Scan using Trivy Scanner

on:
  workflow_dispatch:

jobs:
  build-scan-image:
    name: Build & Scan Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up JDK build environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      #Build image for scanning
      - name: Build image from Dockerfile
        run: |
          docker build -t digital-forms-api:latest .
      
      #Run Vulnerability Scan usinig Trivy scanner
      - name: Run Trivy vulnerability scanner 
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: digital-forms-api:latest
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL